"""empty message

Revision ID: 07a65e642a2f
Revises: 0d81e10be76f
Create Date: 2018-12-06 19:14:35.812486+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '07a65e642a2f'
down_revision = '0d81e10be76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=256), nullable=True),
    sa.Column('citation', sa.String(length=1000), nullable=False),
    sa.Column('year_created', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=256), nullable=True),
    sa.Column('num_cat', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    # ### end Alembic commands ###
