"""

Revision ID: 142e58e1e9da
Revises: 
Create Date: 2018-11-17 22:59:03.910124+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '142e58e1e9da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_dataset_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('dataset_name', sa.String(length=1000), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_dataset_request_email'), 'add_dataset_request', ['email'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=256), nullable=True),
    sa.Column('citation', sa.String(length=1000), nullable=False),
    sa.Column('year_created', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=256), nullable=True),
    sa.Column('num_cat', sa.String(length=256), nullable=True),
    sa.Column('contact_name', sa.String(length=256), nullable=False),
    sa.Column('contact_email', sa.String(length=256), nullable=False),
    sa.Column('related_paper', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delete_dataset_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delete_dataset_request_email'), 'delete_dataset_request', ['email'], unique=False)
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'dataset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_index(op.f('ix_delete_dataset_request_email'), table_name='delete_dataset_request')
    op.drop_table('delete_dataset_request')
    op.drop_table('users')
    op.drop_table('tag')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_add_dataset_request_email'), table_name='add_dataset_request')
    op.drop_table('add_dataset_request')
    # ### end Alembic commands ###
