"""empty message

Revision ID: 27ff1a641b21
Revises: 142e58e1e9da
Create Date: 2018-11-19 06:33:23.759892+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '27ff1a641b21'
down_revision = '142e58e1e9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_dataset_request', sa.Column('reason', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete_dataset_request', 'reason')
    # ### end Alembic commands ###
