"""

Revision ID: 3b7cdbfbd15d
Revises: 39d17776c5c0
Create Date: 2018-11-05 19:25:26.712816+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7cdbfbd15d'
down_revision = '39d17776c5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'thumbnail',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('datasets', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('datasets', 'thumbnail',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
