"""empty message

Revision ID: 582d744549fe
Revises: da9bc40d1cb9
Create Date: 2018-11-25 02:50:14.794159+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '582d744549fe'
down_revision = 'da9bc40d1cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
