"""empty message

Revision ID: 6c0dc56331c3
Revises: 030a7ac76870
Create Date: 2018-11-23 02:29:16.747833+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6c0dc56331c3'
down_revision = '030a7ac76870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'category')
    # ### end Alembic commands ###
