"""empty message

Revision ID: 6e2c62a41e77
Revises: 582d744549fe
Create Date: 2018-11-25 02:51:33.004548+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6e2c62a41e77'
down_revision = '582d744549fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delete_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('edit_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('delete_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
