"""empty message

Revision ID: 79f0d4db4f49
Revises: 75a6e59c5c24
Create Date: 2018-12-21 05:06:38.700937+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '79f0d4db4f49'
down_revision = '75a6e59c5c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
