"""empty message

Revision ID: 918070bc49d0
Revises: f3813965ac77
Create Date: 2019-02-24 18:55:47.433775+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '918070bc49d0'
down_revision = 'f3813965ac77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
