"""empty message

Revision ID: a575c23344a4
Revises: 27ff1a641b21
Create Date: 2018-11-19 16:16:08.443643+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a575c23344a4'
down_revision = '27ff1a641b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_dataset_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=1000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('create_dataset_key')
    # ### end Alembic commands ###
