"""empty message

Revision ID: ab93d9d45d5e
Revises: 21f9e7d0aad5
Create Date: 2018-12-31 03:29:50.986481+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ab93d9d45d5e'
down_revision = '21f9e7d0aad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
