"""empty message

Revision ID: abf56a168c2d
Revises: 6c0dc56331c3
Create Date: 2018-11-24 23:41:45.196027+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'abf56a168c2d'
down_revision = '6c0dc56331c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_dataset_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_dataset_request_email'), 'edit_dataset_request', ['email'], unique=False)
    op.drop_column('datasets', 'related_paper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('related_paper', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_edit_dataset_request_email'), table_name='edit_dataset_request')
    op.drop_table('edit_dataset_request')
    # ### end Alembic commands ###
