"""empty message

Revision ID: be8414cdbb75
Revises: c6f769ccfb1f
Create Date: 2019-01-04 21:54:23.016489+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'be8414cdbb75'
down_revision = 'c6f769ccfb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('edit_request_messages', sa.Column('edit_request_id', sa.Integer(), nullable=False))
    op.drop_constraint('edit_request_messages_dataset_id_fkey', 'edit_request_messages', type_='foreignkey')
    op.create_foreign_key(None, 'edit_request_messages', 'edit_requests', ['edit_request_id'], ['id'])
    op.drop_column('edit_request_messages', 'is_new_request')
    op.drop_column('edit_request_messages', 'dataset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edit_request_messages', sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('edit_request_messages', sa.Column('is_new_request', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'edit_request_messages', type_='foreignkey')
    op.create_foreign_key('edit_request_messages_dataset_id_fkey', 'edit_request_messages', 'datasets', ['dataset_id'], ['id'])
    op.drop_column('edit_request_messages', 'edit_request_id')
    op.drop_table('edit_requests')
    # ### end Alembic commands ###
