"""empty message

Revision ID: c6f769ccfb1f
Revises: ab93d9d45d5e
Create Date: 2019-01-04 21:07:22.964659+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c6f769ccfb1f'
down_revision = 'ab93d9d45d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edit_request_messages', sa.Column('has_admin_read', sa.Boolean(), nullable=True))
    op.add_column('edit_request_messages', sa.Column('has_owner_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edit_request_messages', 'has_owner_read')
    op.drop_column('edit_request_messages', 'has_admin_read')
    # ### end Alembic commands ###
