"""empty message

Revision ID: cab45341997b
Revises: c5dbefa6344c
Create Date: 2019-02-24 19:11:17.665396+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cab45341997b'
down_revision = 'c5dbefa6344c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
