"""empty message

Revision ID: d3db0815ecd7
Revises: b382c772057e
Create Date: 2019-01-08 18:30:27.351422+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd3db0815ecd7'
down_revision = 'b382c772057e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
