"""empty message

Revision ID: da9bc40d1cb9
Revises: abf56a168c2d
Create Date: 2018-11-24 23:57:09.662615+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'da9bc40d1cb9'
down_revision = 'abf56a168c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delete_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('delete_dataset_request', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('delete_dataset_request', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('delete_dataset_request', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index('ix_delete_dataset_request_email', table_name='delete_dataset_request')
    op.alter_column('edit_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('edit_dataset_request', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('edit_dataset_request', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('edit_dataset_request', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_dataset_request', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('edit_dataset_request', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('edit_dataset_request', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('edit_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_delete_dataset_request_email', 'delete_dataset_request', ['email'], unique=False)
    op.alter_column('delete_dataset_request', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('delete_dataset_request', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('delete_dataset_request', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('delete_dataset_request', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
