"""added_new_citation_fields

Revision ID: 0b7612ec5fcb
Revises: fb61fa05e791
Create Date: 2019-10-24 19:35:19.325818+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0b7612ec5fcb'
down_revision = 'fb61fa05e791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('cite_authors', sa.String(length=1000), nullable=True))
    op.add_column('datasets', sa.Column('cite_title', sa.String(length=1000), nullable=True))
    op.add_column('datasets', sa.Column('cite_venue', sa.String(length=1000), nullable=True))
    op.add_column('datasets', sa.Column('cite_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'cite_year')
    op.drop_column('datasets', 'cite_venue')
    op.drop_column('datasets', 'cite_title')
    op.drop_column('datasets', 'cite_authors')
    # ### end Alembic commands ###
