"""revert update citation field

Revision ID: 0ced7f403f3d
Revises: a0ea2056bab3
Create Date: 2019-10-24 19:09:57.893989+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0ced7f403f3d'
down_revision = 'a0ea2056bab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('citation', sa.String(length=1000), nullable=True))
    op.drop_column('datasets', 'cite_year')
    op.drop_column('datasets', 'cite_authors')
    op.drop_column('datasets', 'cite_title')
    op.drop_column('datasets', 'cite_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('cite_venue', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('datasets', sa.Column('cite_title', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('datasets', sa.Column('cite_authors', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('datasets', sa.Column('cite_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('datasets', 'citation')
    # ### end Alembic commands ###
