"""empty message

Revision ID: 0d81e10be76f
Revises: dd0b6577090a
Create Date: 2018-12-06 19:12:50.367911+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0d81e10be76f'
down_revision = 'dd0b6577090a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
