"""added_new_citation_fields

Revision ID: 4e74d63529f4
Revises: 0b7612ec5fcb
Create Date: 2019-10-24 20:59:11.583861+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4e74d63529f4'
down_revision = '0b7612ec5fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
