"""added_new_citation_fields

Revision ID: 6895f8d0c178
Revises: 4e74d63529f4
Create Date: 2019-10-24 21:00:59.298695+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6895f8d0c178'
down_revision = '4e74d63529f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
