"""empty message

Revision ID: 6bf80b28f9fd
Revises: cab45341997b
Create Date: 2019-02-24 19:13:46.556771+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6bf80b28f9fd'
down_revision = 'cab45341997b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
