"""empty message

Revision ID: 75a6e59c5c24
Revises: c620400e93d6
Create Date: 2018-12-07 18:06:55.373595+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '75a6e59c5c24'
down_revision = 'c620400e93d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'datasets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'owner_id')
    # ### end Alembic commands ###
