"""rename_citation_field_new

Revision ID: 9cc3f23d0b5b
Revises: cd13e8384e0a
Create Date: 2019-10-24 19:19:02.836175+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9cc3f23d0b5b'
down_revision = 'cd13e8384e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'citation', new_column_name='old_citation')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
