"""update citation field

Revision ID: a0ea2056bab3
Revises: 35528a030ae2
Create Date: 2019-10-24 19:06:02.448654+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a0ea2056bab3'
down_revision = '35528a030ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('cite_authors', sa.String(length=1000), nullable=True))
    op.add_column('datasets', sa.Column('cite_title', sa.String(length=1000), nullable=True))
    op.add_column('datasets', sa.Column('cite_venue', sa.String(length=1000), nullable=True))
    op.add_column('datasets', sa.Column('cite_year', sa.Integer(), nullable=True))
    op.drop_column('datasets', 'citation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('citation', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('datasets', 'cite_year')
    op.drop_column('datasets', 'cite_venue')
    op.drop_column('datasets', 'cite_title')
    op.drop_column('datasets', 'cite_authors')
    # ### end Alembic commands ###
