"""rename_citation_field

Revision ID: a7ed5e3064bc
Revises: 0ced7f403f3d
Create Date: 2019-10-24 19:11:20.680187+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a7ed5e3064bc'
down_revision = '0ced7f403f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('old_citation', sa.String(length=1000), nullable=True))
    op.drop_column('datasets', 'citation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('citation', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('datasets', 'old_citation')
    # ### end Alembic commands ###
