"""empty message

Revision ID: abee9be7c5e2
Revises: 51407cbc10a9
Create Date: 2019-06-06 01:07:38.403888+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'abee9be7c5e2'
down_revision = '51407cbc10a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
