"""empty message

Revision ID: c5dbefa6344c
Revises: 918070bc49d0
Create Date: 2019-02-24 18:59:47.025660+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c5dbefa6344c'
down_revision = '918070bc49d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
