"""rename_citation_field_new

Revision ID: fb61fa05e791
Revises: 9cc3f23d0b5b
Create Date: 2019-10-24 19:30:58.055047+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fb61fa05e791'
down_revision = '9cc3f23d0b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
